<?php $viewModel = $block->getViewModel() ?>
<form class="form contact"
      action="<?= $block->getUrl('training_feedback/index/save') ?>"
      id="feedback-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= $block->escapeHtml(__('Leave your feedback')) ?></span>
        </legend>
        <div class="field name required">
            <label class="label" for="author_name">
                <span><?= $block->escapeHtml(__('Name')) ?></span>
            </label>
            <div class="control">
                <input name="author_name" id="author_name"
                       title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value=""
                       class="input-text" type="text" data-validate="{required:true}" />
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="author_email">
                <span><?= $block->escapeHtml(__('Email')) ?></span>
            </label>
            <div class="control">
                <input name="author_email" id="author_email"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value=""
                       class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="message">
                <span><?= $block->escapeHtml(__('Whats on your mind?')) ?></span>
            </label>
            <div class="control">
                <textarea name="message" id="message"
                          title="<?= $block->escapeHtmlAttr(__('Whats on your mind?')) ?>"
                          class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= $block->escapeHtml(__('Submit')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>

            </div>
        </div>
    </fieldset>
</form>
